/* Classroom content follows the assigned COMPAS discussion questions. */
window.LAB_CONTENT={
 names:['Lobby','Opening vote','Fairness face-off','Stakeholder discussion','Race as an input','Threshold lab','Beyond equal errors','Who decides?','Team principles','Final vote'],
 stakeholders:{scientists:'Data scientists',vendor:'COMPAS vendor',judges:'Judges',legislators:'Legislators',defendants:'Defendants',communities:'Affected communities'},
 principles:{accuracy:'Accuracy and calibration',subgroups:'Subgroup error monitoring',transparency:'Transparency and explanations',appeal:'Ability to contest decisions',human:'Meaningful human review',purpose:'Clear limits on use',labels:'Audit the target and labels',monitoring:'Ongoing deployment monitoring'},
 trust:{algorithm:'Algorithmic assessment (COMPAS)',judge:'A human judge',safeguards:'Neither without specified safeguards',unsure:'Not enough information'},
 activities:{
 1:{key:'initial',title:'Who would you trust with this decision?',question:'If you were awaiting trial, would you rather have your risk assessed by COMPAS or by a human judge?',kind:'poll',follow:'What would you need to know about each before deciding?',notes:'Take two contrasting reasons. Do not equate a risk assessment with a final judicial decision. Save the discussion of safeguards for the debrief.'},
 2:{key:'fairness',title:'Same evidence. Different fairness questions.',question:'Which fairness criterion would you prioritize for this use, and why?',kind:'poll',options:{errors:'Equalize error rates',calibration:'Preserve the meaning of risk scores',context:'The choice depends on the decision context',unsure:'I need more information'},follow:'What did ProPublica call unfair? What did Northpointe defend as fair? If both statistics are correct, what is the disagreement about?',notes:'Distinguish conditioning on observed outcomes (FPR/FNR) from conditioning on a score (calibration). Calibration and positive predictive value of a thresholded category are related but not identical. Changing a threshold alone does not change calibration of the underlying score.'},
 3:{key:'breakout',title:'A stakeholder roundtable',question:'From your assigned perspective, which concern would you prioritize, what trade-off would you accept, and who would bear its cost?',kind:'discussion',follow:'Each group: give one principle, one cost, and one safeguard in 30 seconds.',notes:'Allow groups to reject the framing. These are starting perspectives, not claims that everyone in a stakeholder group agrees. Use 4 minutes for discussion and 2 minutes for reports.'},
 4:{key:'race',title:'What does “we do not use race” establish?',question:'If removing race as an input does not remove disparities, how much assurance does that claim provide?',kind:'poll',options:{enough:'Enough assurance for this use',limited:'A useful constraint, but insufficient evidence of fairness',insufficient:'Little assurance without examining the data and outcomes',unsure:'I need more information'},follow:'Where else might disparities enter: labels, proxies, sampling, thresholds, or deployment?',notes:'Do not assume correlation with race makes every feature illegitimate. Ask what a variable measures and how it was produced. Observed rearrest is not a complete measure of criminal behavior.'},
 5:{key:'threshold',title:'What changes when the stakes change?',question:'Choose a threshold, inspect the resulting errors, then submit your choice.',kind:'threshold',follow:'Who bears each error? Would you keep the same threshold if the consequence changed?',notes:'This is a toy dataset with 200 observations: 100 recorded positives and 100 negatives. It is not COMPAS data and does not establish a fairness-impossibility theorem. High-risk classification is not automatically a detention order. Run detention first, close and discuss, then switch to support.'},
 6:{key:'equal',title:'Equal errors. Is the decision settled?',question:'Imagine a system has equal false-positive and false-negative rates across the racial groups audited. Would that be enough to justify using it to help decide pretrial detention?',kind:'poll',options:{yes:'Yes, that would address my main concern',no:'No, other concerns would remain',depends:'It depends on other safeguards and evidence',unsure:'I am not sure'},follow:'Should predicted future risk affect liberty before trial? What concern remains, and could any of our mathematical metrics detect it?',notes:'Use the assigned equal-error thought experiment. You may separately ask whether very high accuracy changes anyone\'s view. Do not assert simultaneous perfect calibration, equal error rates, and 99.9% accuracy with unequal base rates.'},
 7:{key:'tokens',title:'Who should choose the fairness standard?',question:'Allocate exactly 10 influence tokens across these six stakeholders.',kind:'tokens',follow:'Who effectively selected the standards in the original COMPAS debate? Who should participate in selecting them?',notes:'Tokens are a discussion device, not a legal voting mechanism. Ask students to explain roles and accountability, not just who received the most tokens. Only complete 10-token allocations are counted.'},
 8:{key:'principles',title:'Your team’s non-negotiables',question:'Choose two or three principles for a team developing, evaluating, or deploying a tool like COMPAS.',kind:'principles',follow:'What about this case makes each principle important? Name a concrete action your team would take.',notes:'Turn values into actions: which target, which audit, what appeal route, what limit on use? Avoid claiming that a toolkit can certify a system as fair.'},
 9:{key:'final',title:'Revisit your starting point',question:'After the discussion, would you rather have your risk assessed by COMPAS or by a human judge?',kind:'poll',follow:'Did your answer change? Which evidence or condition mattered? Name a concern that no fairness metric alone could resolve.',notes:'The opening and final options are identical. Matched change counts include only browsers that submitted both. This is a classroom reflection, not a causal study of persuasion.'}
 },
 roles:[
 {name:'A · Defendants and civil-rights advocates',prompt:'Consider false positives, access to explanations, and the ability to challenge a score. What else matters from this perspective?'},
 {name:'B · Model developers',prompt:'Consider predictive validity, score interpretation, and deployment limits. What trade-offs should developers disclose?'},
 {name:'C · Judges and public-safety officials',prompt:'Consider both missed risks and unnecessary restrictions. What evidence should a judge require beyond a score?'},
 {name:'D · Community representatives',prompt:'Consider who chooses the goal, who bears the effects, and whether prediction is appropriate for this decision at all.'}
 ],
 sources:[
 ['ProPublica · Machine Bias (2016)','https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing'],
 ['ProPublica · Mathematical trade-offs (2016)','https://www.propublica.org/article/bias-in-criminal-risk-scores-is-mathematically-inevitable-researchers-say'],
 ['Feller et al. · Washington Post analysis (2016)','https://perma.cc/KYC8-KYGD'],
 ['Hao and Stray · Courtroom algorithm game (2019)','https://www.technologyreview.com/2019/10/17/75285/ai-fairer-than-judge-criminal-risk-assessment-algorithm/']
 ]
};
LAB_CONTENT.activities[1].options=LAB_CONTENT.trust;
LAB_CONTENT.activities[9].options=LAB_CONTENT.trust;
