const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {};
context.window = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync('content.js','utf8'),context);
const c=context.LAB_CONTENT;
assert.equal(JSON.stringify(c.order),JSON.stringify([0,10,1,2,3,4,5,6,7,8,9]));
assert.equal(c.activities[10].kind,'briefing');
assert.equal(JSON.stringify(Object.keys(c.readingEvidence)),JSON.stringify(['2','4','5','7']));
assert.ok(Object.values(c.activities).every(a=>!Object.hasOwn(a,'notes')));
assert.equal(JSON.stringify(c.activities[1].options),JSON.stringify(c.activities[9].options));
const js=fs.readFileSync('classroom.js','utf8');
assert.ok(!js.includes('Facilitator notes'));
assert.ok(js.includes('Start case introduction'));
assert.ok(js.includes('Open opening vote'));
assert.ok(js.includes("command('reading',!state.reading_visible)"));
console.log('PASS: briefing order, source-only reveals, no private presentation notes, identical opening/final options.');
